export const stickers = [
    { name: 'Grinning Face', emoji: '😀', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f600.svg' },
    { name: 'Beaming Face with Smiling Eyes', emoji: '😁', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f601.svg' },
    { name: 'Face with Tears of Joy', emoji: '😂', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f602.svg' },
    { name: 'Smiling Face with Heart-Eyes', emoji: '😍', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f60d.svg' },
    { name: 'Winking Face', emoji: '😉', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f609.svg' },
    { name: 'Thinking Face', emoji: '🤔', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f914.svg' },
    { name: 'Face with Sunglasses', emoji: '😎', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f60e.svg' },
    { name: 'Party Popper', emoji: '🎉', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f389.svg' },
    { name: 'Red Heart', emoji: '❤️', url: 'https://twemoji.maxcdn.com/v/latest/svg/2764.svg' },
    { name: 'Fire', emoji: '🔥', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f525.svg' },
    { name: 'Sparkles', emoji: '✨', url: 'https://twemoji.maxcdn.com/v/latest/svg/2728.svg' },
    { name: 'Thumbs Up', emoji: '👍', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f44d.svg' },
    { name: 'Clapping Hands', emoji: '👏', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f44f.svg' },
    { name: 'Rocket', emoji: '🚀', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f680.svg' },
    { name: 'Hundred Points', emoji: '💯', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f4af.svg' },
    { name: 'Cat with Tears of Joy', emoji: '😹', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f639.svg' },
    { name: 'Ghost', emoji: '👻', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f47b.svg' },
    { name: 'Pizza', emoji: '🍕', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f355.svg' },
    { name: 'Taco', emoji: '🌮', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f32e.svg' },
    { name: 'Unicorn', emoji: '🦄', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f984.svg' },
    { name: 'Brain', emoji: '🧠', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f9e0.svg' },
    { name: 'Exploding Head', emoji: '🤯', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f92f.svg' },
    { name: 'Money-Mouth Face', emoji: '🤑', url: 'https://twemoji.maxcdn.com/v/latest/svg/1f911.svg' }
];
